export const LMU_TRACKS = [
  {
    group: "Le Mans Ultimate",
    options: [
      "Algarve International Circuit (Portimão)",
      "Autodromo Internazionale Enzo e Dino Ferrari (Imola) (2024 Pack 1 DLC)",
      "Autódromo José Carlos Pace (Interlagos) (2024 Pack 3 DLC)",
      "Bahrain International Circuit",
      "Circuit of the Americas (2024 Pack 2 DLC)",
      "Circuit de la Sarthe",
      "Daytona International Speedway",
      "Fuji International Speedway",
      "Laguna Seca (WeatherTech Raceway)",
      "Lusail International Circuit (2024 Pack 5 DLC)",
      "Monza",
      "Sebring",
      "Spa-Francorchamps",
    ],
  },
  {
    group: "ELMS",
    options: [
      "Circuit de Barcelona-Catalunya (ELMS Pack 3 DLC)",
      "Circuit Paul Ricard (ELMS Pack 2 DLC)",
      "Silverstone (ELMS Pack 1 DLC)",
    ],
  },
  {
    group: "Layouts alternatifs",
    options: [
      "Algarve International Circuit (Portimão) ELMS",
      "Autodromo Internazionale Enzo e Dino Ferrari (Imola) ELMS (2024 Pack 1 DLC)",
      "Bahrain International Endurance Circuit",
      "Bahrain International Outer Circuit",
      "Bahrain International Paddock Circuit",
      "COTA National",
      "Circuit de la Sarthe Mulsanne No Chicanes",
      "Fuji Classic Layout (No Chicane)",
      "Lusail International Circuit Short",
      "Monza Curva Grande Layout",
      "Paul Ricard 1a",
      "Paul Ricard 1av2",
      "Paul Ricard 1av2-short",
      "Paul Ricard 3a",
      "Sebring School Circuit",
      "Silverstone GP (WEC)",
      "Silverstone International",
      "Silverstone National",
      "Spa Endurance Layout (62-car support)",
    ],
  },
  {
    group: "Mystère",
    options: ["Mystère"],
  },
];
